### PR TITLE
Update licensing - Release the XBlock under the AGPLv3 license

### PR DESCRIPTION
**Pull request by antoviaque**
@zvishal See the README file and the license notice, and let me know if you'd like any changes.

FYI @Kelketek

### CODE REVIEW

**Comment by andyparsons** [comment]
@antoviaque @Kelketek @zvishal very happy to see this commit come through- this is a great milestone for our extended team!

**Comment by antoviaque** [comment]
Thanks for this @andyparsons ! Definitely a great step, ti's good to know this XBlock will be useful to the community as a whole : )

**Comment by Kelketek** [comment]
Thank you @andyparsons @antoviaque @zvishal . I look forward to working with the community on this software and seeing it benefit more people. :)

**Comment by zvishal** [comment]
LGTM. @Kelketek @antoviaque thank you! you guys rock!

**Pull request merged**
